import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { getHealthCheckForUser } from "@/lib/health-check/data";
import { PrintButton } from "@/components/PrintButton";
import { SECTIONS, findQuestion } from "@/lib/health-check/questions";

export default async function ComplianceKitPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await auth();
  if (!session) redirect("/login");

  const { id } = await params;
  const result = await getHealthCheckForUser(session.user.id, id);
  if (!result) notFound();

  const { healthCheck } = result;

  const gaps = healthCheck.answers
    .filter((a) => a.value !== "YES")
    .map((a) => ({ answer: a, lookup: findQuestion(a.questionId) }))
    .filter((g): g is typeof g & { lookup: NonNullable<typeof g.lookup> } => !!g.lookup);

  const gapsBySection = SECTIONS.map((section) => ({
    section,
    items: gaps.filter((g) => g.lookup.section.key === section.key),
  })).filter((g) => g.items.length > 0);

  return (
    <div className="mx-auto max-w-3xl px-8 py-10">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <p className="text-sm text-gray-500">Action list generated from the gaps found in this health check.</p>
        <PrintButton />
      </div>

      <div className="mb-8 flex items-center gap-3 border-b-2 border-gray-900 pb-4">
        <div className="flex h-10 w-10 items-center justify-center rounded bg-gray-900 text-sm font-bold text-white">
          CC
        </div>
        <span className="text-lg font-semibold">Compliance Console</span>
      </div>

      <p className="text-xs uppercase tracking-wide text-gray-400">Compliance Kit</p>
      <h1 className="mb-1 text-xl font-semibold">{healthCheck.organisation.name}</h1>
      <p className="mb-8 text-sm text-gray-500">
        Built from health check version {healthCheck.version}, run{" "}
        {healthCheck.createdAt.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}.
      </p>

      {gapsBySection.length === 0 ? (
        <div className="rounded-lg border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">
          No gaps found — every question was answered Yes.
        </div>
      ) : (
        <div className="flex flex-col gap-8">
          {gapsBySection.map(({ section, items }) => (
            <div key={section.key}>
              <h2 className="mb-3 text-base font-semibold">{section.label}</h2>
              <ul className="flex flex-col gap-4">
                {items.map(({ answer, lookup }) => (
                  <li key={answer.id} className="flex gap-3 border-b border-gray-100 pb-4 last:border-0">
                    <input type="checkbox" className="mt-1" disabled />
                    <div>
                      <p className="text-sm font-medium">{lookup.question.text}</p>
                      <p className="text-xs text-gray-400">
                        Current answer: {answer.value === "PARTIAL" ? "Partially" : "No"}
                      </p>
                      <p className="mt-1 text-sm text-gray-700">{lookup.question.remediation}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      <p className="mt-10 text-xs text-gray-400">
        Generated by Compliance Console. Treat this as a starting action list, not a substitute for professional
        advice.
      </p>
    </div>
  );
}
