import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { getHealthCheckForUser } from "@/lib/health-check/data";
import { HealthCheckReport } from "@/components/HealthCheckReport";
import { PrintButton } from "@/components/PrintButton";

export default async function PrintHealthCheckPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await auth();
  if (!session) redirect("/login");

  const { id } = await params;
  const result = await getHealthCheckForUser(session.user.id, id);
  if (!result) notFound();

  const { healthCheck, sectionScoreMap, previous, previousSectionScoreMap } = result;

  return (
    <div className="mx-auto max-w-3xl px-8 py-10">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <p className="text-sm text-gray-500">Branded report preview — colours/logo are placeholders.</p>
        <PrintButton />
      </div>

      <div className="mb-8 flex items-center gap-3 border-b-2 border-gray-900 pb-4">
        <div className="flex h-10 w-10 items-center justify-center rounded bg-gray-900 text-sm font-bold text-white">
          CC
        </div>
        <span className="text-lg font-semibold">Compliance Console</span>
      </div>

      <HealthCheckReport
        organisationName={healthCheck.organisation.name}
        version={healthCheck.version}
        createdAt={healthCheck.createdAt}
        createdByLabel={healthCheck.createdBy.name ?? healthCheck.createdBy.email}
        overallScore={healthCheck.overallScore}
        previousOverallScore={previous?.overallScore ?? null}
        sectionScoreMap={sectionScoreMap}
        previousSectionScoreMap={previousSectionScoreMap}
      />

      <p className="mt-10 text-xs text-gray-400">
        Generated by Compliance Console. This health check reflects self-reported answers at the time it was run
        and is not a substitute for professional advice.
      </p>
    </div>
  );
}
